[book]
title = "catnip"
authors = ["bsuth"]
language = "en"
src = "docs"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/bsuth/catnip"

[output.html.code.hidelines]
lua = "!"
